"use client";

import { useEffect, useState } from "react";

type Rate = { id: number; provider_name: string; rate_type: string; rate_value: string; effective_date: string; ingested_at: string };
type History = { results: Rate[] };
const api = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000";

export default function Home() {
  const [rates, setRates] = useState<Rate[]>([]); const [selected, setSelected] = useState<Rate>();
  const [history, setHistory] = useState<Rate[]>([]); const [sort, setSort] = useState<"rate_value" | "effective_date">("rate_value");
  const [latestState, setLatestState] = useState("Loading current rates"); const [historyState, setHistoryState] = useState("Choose a rate to view history");
  useEffect(() => { let alive = true; const load = async () => { try { const data: Rate[] = await fetch(`${api}/rates/latest`).then(r => r.ok ? r.json() : Promise.reject()); if (alive) { setRates(data); setSelected(current => current || data[0]); setLatestState(data.length ? "" : "No current rates are available."); } } catch { if (alive) setLatestState("Current rates could not be loaded. Retry in a moment."); } }; load(); const id = setInterval(load, 60000); return () => { alive = false; clearInterval(id); }; }, []);
  useEffect(() => { if (!selected) return; let alive = true; setHistoryState("Loading 30-day history"); const from = new Date(selected.effective_date); from.setDate(from.getDate() - 30); fetch(`${api}/rates/history?provider=${encodeURIComponent(selected.provider_name)}&type=${encodeURIComponent(selected.rate_type)}&from=${from.toISOString().slice(0, 10)}&page_size=100`).then(r => r.ok ? r.json() : Promise.reject()).then((data: History) => { if (alive) { setHistory(data.results); setHistoryState(data.results.length ? "" : "No records were available in this 30-day window."); } }).catch(() => alive && setHistoryState("History could not be loaded.")); return () => { alive = false; }; }, [selected]);
  const ordered = [...rates].sort((a, b) => sort === "rate_value" ? Number(a.rate_value) - Number(b.rate_value) : b.effective_date.localeCompare(a.effective_date));
  const points = history.map((rate, index) => `${history.length < 2 ? 50 : (index / (history.length - 1)) * 100},${100 - ((Number(rate.rate_value) - Math.min(...history.map(x => Number(x.rate_value)))) / Math.max(0.01, Math.max(...history.map(x => Number(x.rate_value))) - Math.min(...history.map(x => Number(x.rate_value))))) * 100}`).join(" ");
  return <main><header><p className="eyebrow">Forbes Advisor assessment</p><h1>Rate tracker</h1><p>Live provider comparison, refreshed every minute.</p></header><section className="table"><div className="section-head"><h2>Latest rate by provider</h2><div><button onClick={() => setSort("rate_value")}>Sort by value</button><button onClick={() => setSort("effective_date")}>Sort by update</button></div></div>{latestState ? <p className="state">{latestState}</p> : <div className="scroll"><table><thead><tr><th>Provider</th><th>Type</th><th>Rate</th><th>Updated</th></tr></thead><tbody>{ordered.map(rate => <tr key={rate.id} onClick={() => setSelected(rate)} className={selected?.id === rate.id ? "selected" : ""}><td>{rate.provider_name}</td><td>{rate.rate_type.replaceAll("_", " ")}</td><td>{rate.rate_value}%</td><td>{rate.effective_date}</td></tr>)}</tbody></table></div>}</section><section className="chart"><div><p className="eyebrow">30-day movement</p><h2>{selected ? `${selected.provider_name} / ${selected.rate_type.replaceAll("_", " ")}` : "Select a rate"}</h2></div>{historyState ? <p className="state">{historyState}</p> : <svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Rate history line chart"><polyline points={points} /></svg>}</section></main>;
}
