# Generated by Django 5.1.7 on 2026-07-18 07:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('source_identifier', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('partially_succeeded', 'Partially succeeded'), ('failed', 'Failed')], default='started', max_length=24)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_identifier'), name='unique_ingestion_source_identifier')],
            },
        ),
        migrations.CreateModel(
            name='RawRateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveBigIntegerField()),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='rates.ingestionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='RateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=128)),
                ('rate_type', models.CharField(max_length=64)),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField()),
                ('ingested_at', models.DateTimeField()),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rate_record', to='rates.rawraterecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='rawraterecord',
            index=models.Index(fields=['batch', 'parse_status'], name='raw_batch_parse_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawraterecord',
            constraint=models.UniqueConstraint(fields=('batch', 'source_row_number'), name='unique_raw_batch_row'),
        ),
        migrations.AddIndex(
            model_name='raterecord',
            index=models.Index(fields=['provider_name', '-effective_date', '-ingested_at', '-id'], name='rate_latest_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='raterecord',
            index=models.Index(fields=['rate_type', 'provider_name', '-effective_date', '-ingested_at', '-id'], name='rate_latest_type_idx'),
        ),
        migrations.AddIndex(
            model_name='raterecord',
            index=models.Index(fields=['provider_name', 'rate_type', '-effective_date'], name='rate_history_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='raterecord',
            index=models.Index(fields=['ingested_at'], name='rate_ingested_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='raterecord',
            constraint=models.UniqueConstraint(fields=('provider_name', 'rate_type', 'effective_date', 'rate_value'), name='unique_normalized_rate_fact'),
        ),
        migrations.AddConstraint(
            model_name='raterecord',
            constraint=models.CheckConstraint(condition=models.Q(('rate_value__gt', 0)), name='rate_value_positive'),
        ),
    ]
